In [24]:
import pandas as pd , numpy as np 
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedShuffleSplit , cross_val_score 
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

data=pd.read_csv("practicing.csv")
data.head()
data_2=data.copy()
data_2

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,INLAND
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,77100,INLAND
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,INLAND
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,INLAND
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,INLAND

In [14]:
# We can fill the gap via pd or directly use the feature of machine learning via creating a pipeline
data_copy=data.copy()
data_copy['total_bedrooms']=data_copy['total_bedrooms'].fillna(data['total_bedrooms'].mean())
data_copy.isnull().sum()
data_copy['total_bedrooms'].isnull().sum()

np.int64(0)

In [33]:
data_2_features=data_2.drop("ocean_proximity",axis=1)
data_2_labels=data_2[['ocean_proximity']]

number_pipeline=Pipeline([
    ['Impute',SimpleImputer(strategy='mean')]
])

# features_pipeline=Pipeline([
#     ['Encoder',OneHotEncoder(handle_unknown='ignore')]
    
# ])
# full_pipeline=ColumnTransformer([
#     ('numbers',number_pipeline,data_2_features.columns),
#     ('features',features_pipeline,['ocean_proximity'])
# ])
# converting=full_pipeline.fit_transform(data_2)
# dataframing=pd.DataFrame(converting,columns=full_pipeline.get_feature_names_out(),index=data_2.index)
# dataframing
# data_2_labels

# Do concatination for the splitting the size
concatination=pd.concat([dataframing,data_2_labels],axis=1)
concatination

# Now the data visualization is present here and we will do 
# import matplotlib.pyplot as plt 
# dataframing.plot(kind='scatter',x='numbers__latitude',y='numbers__longitude',cmap='inferno',c='numbers__latitude')
# plt.grid(True)
# plt.title("Housing")
# plt.show()

,numbers__longitude,numbers__latitude,numbers__housing_median_age,numbers__total_rooms,numbers__total_bedrooms,numbers__population,numbers__households,numbers__median_income,numbers__median_house_value,features__ocean_proximity_<1H OCEAN,features__ocean_proximity_INLAND,features__ocean_proximity_ISLAND,features__ocean_proximity_NEAR BAY,features__ocean_proximity_NEAR OCEAN,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,0.0,0.0,0.0,1.0,0.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,0.0,0.0,0.0,1.0,0.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,0.0,0.0,0.0,1.0,0.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,0.0,0.0,0.0,1.0,0.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,0.0,0.0,0.0,1.0,0.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,0.0,1.0,0.0,0.0,0.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,0.0,1.0,0.0,0.0,0.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,0.0,1.0,0.0,0.0,0.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,0.0,1.0,0.0,0.0,0.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,0.0,1.0,0.0,0.0,0.0,INLAND

In [45]:
# Now split the data on which we have done all the work for better kinda work
import joblib
import os 
import numpy as np

MODEL='model.pkl'
DATA='data.pkl'

if not os.path.exists(MODEL):
   data_2_features=data_2.drop("median_house_value",axis=1)
   data_2_labels=data_2[['median_house_value']]

   numbers_columns=data_2_features.select_dtypes(include=np.number).columns
   cat_columns=['ocean_proximity']
   
   number_pipeline=Pipeline([
       ('Impute',SimpleImputer(strategy='mean'))
   ])
   
   features_pipeline=Pipeline([
       ('Encoder',OneHotEncoder(handle_unknown='ignore'))
       
   ])
   full_pipeline=ColumnTransformer([
       ('numbers',number_pipeline,numbers_columns),
       ('features',features_pipeline,cat_columns)
   ])
   # converting=full_pipeline.fit_transform(data_2)
   # dataframing=pd.DataFrame(converting,columns=full_pipeline.get_feature_names_out(),index=data_2.index)
   # dataframing
   # data_2_labels
   
   splitting=StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
   #I forget here for pd.cut so all the numbers come under both test and train and the string cannot come via that remember
   data_2['number_string']=pd.cut(data_2['median_income'],bins=[-1,1.5,3,4.5,6,7.5,np.inf],labels=[1,2,3,4,5,6])
   for x , y in splitting.split(data_2,data_2['number_string']):
       # We do like this because we want to match the numbers 1,2,3,4,5,6 in both and string variable does not affect it at all
       test_size=data_2.iloc[x]
       train_size=data_2.iloc[y]

   print(train_size)
   x_train=train_size.drop("median_house_value",axis=1)
   y_train=train_size[['median_house_value']]

   x_test=test_size.drop("median_house_value",axis=1)
   y_test=test_size[['median_house_value']]

   x_train_dataset=full_pipeline.fit_transform(x_train)
   x_test_dataset=full_pipeline.transform(x_test)
   
   # Index is false means it does not give an extra table of indexes over there
   
   
   from sklearn.metrics import root_mean_squared_error
   from sklearn.linear_model import LinearRegression
   from sklearn.tree import DecisionTreeRegressor
   from sklearn.ensemble import RandomForestRegressor
   
   regressor_one=train_size.drop(["ocean_proximity","median_house_value"],axis=1)
   regressor_two=train_size[["median_house_value"]]
   
   # Same for RandomForrestClassifier
   forrest=RandomForestRegressor(random_state=42)
   forrest.fit(x_train_dataset,y_train)
   predicting=forrest.predict(x_train_dataset)
   error_two=root_mean_squared_error(y_train,predicting)
   print(f"We got the error_two  for Random Forrest regressor is {error_two}")
   # Regressor_two contains the important array value on which the predicting is used for predict 
   
  
   joblib.dump(forrest,MODEL)
   joblib.dump(full_pipeline,DATA)
   print("MODEL IS TRAINED ! ")
   test_size.to_csv("input.csv",index=False)

else:
    
    load_one=joblib.load(MODEL)
    load_two=joblib.load(DATA)

    test_data=pd.read_csv("input.csv")
    x_new=test_data.drop("median_house_value",axis=1)
    transformer=load_two.transform(x_new)
    predictors_new=load_one.predict(transformer)
    test_data['predicted_median_house_value']=predictors_new

    test_data.to_csv("output.csv",index=False)
    print("Inference is completed and the ML model also !! ")

Inference is completed and the ML model also !!

In [48]:
# Here we now see the value that how much error it has 
new_dataset=pd.read_csv("output.csv")
old_dataset=pd.read_csv("input.csv")
alpha=new_dataset[['predicted_median_house_value']]
beta=old_dataset[['median_house_value']]
concat=pd.concat(

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,number_string,predicted_median_house_value
0,-118.11,34.04,28,3913,696.0,2264,697,5.2446,258000,<1H OCEAN,4,260537.00
1,-118.97,35.38,35,1673,426.0,1041,413,1.3750,57500,INLAND,1,53532.00
2,-117.03,34.07,16,3784,577.0,1615,525,4.2333,220300,INLAND,3,147590.00
3,-122.17,37.43,24,3924,1142.0,7174,950,4.0972,387500,NEAR OCEAN,3,314432.05
4,-121.31,37.96,48,1112,227.0,583,216,2.3393,77600,INLAND,2,82589.00
...,...,...,...,...,...,...,...,...,...,...,...,...
16507,-117.72,33.43,5,1889,359.0,616,246,3.8992,500001,<1H OCEAN,3,206485.07
16508,-120.97,37.65,16,3960,716.0,1776,724,3.9886,137500,INLAND,3,164730.00
16509,-122.58,37.98,52,1180,216.0,467,197,4.9615,292200,NEAR BAY,4,350280.12
16510,-118.44,34.21,37,1665,335.0,1011,343,4.8703,185100,<1H OCEAN,4,223531.00
16511,-116.91,32.81,22,4331,637.0,1952,654,5.4834,232000,<1H OCEAN,4,211065.00